### ISSUE TITLE
the following directives don't match any configuration option: disable-legacy-registry

### ISSUE THREAD

**Issue by jamiejackson** [haxorof/ansible-role-docker-ce#105]
Centos 7.

I'm getting this new-seeming problem in my local development environment and haven't started digging quite yet.

# Docker Version

Installed Packages

- Name        : docker-ce
- Arch        : x86_64
- Epoch       : 3
- Version     : 19.03.0
- Release     : 3.el7
- Size        : 104 M
- Repo        : installed
- From repo   : docker-ce-stable
- Summary     : The open-source application container engine
- URL         : https://www.docker.com
- License     : ASL 2.0

### Ansible Version

```
2.8.2
```

### Role Version
```
2.1.1
```

### Role configuration

```yaml
docker_daemon_config:
  bip: 172.17.0.1/16
  disable-legacy-registry: true
  debug: false
  icc: false
  init: true
  live-restore: false
  log-driver: journald
  storage-driver: overlay2
  userland-proxy: false
```

### Expected Behavior

Docker service starts without errors.

### Actual Behavior

Docker service fails to start:

```
Jul 24 17:44:38 docker-host dockerd[19379]: unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives don't match any configuration option: disable-legacy-registry
Jul 24 17:44:38 docker-host systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Jul 24 17:44:38 docker-host systemd[1]: Failed to start Docker Application Container Engine.
```

**Comment by jamiejackson** [comment]
Okay, I must not have pinned the docker version locally. My servers are running:

Available Packages

- Name        : docker-ce
- Arch        : x86_64
- Epoch       : 3
- Version     : 18.09.7
- Release     : 3.el7
- Size        : 19 M
- Repo        : docker-ce-stable/x86_64
- Summary     : The open-source application

So `disable-legacy-registry` is probably just deprecated.

**Comment by jamiejackson** [comment]
Confirmed: https://docs.docker.com/engine/deprecated/#--disable-legacy-registry-override-daemon-option

**Comment by jamiejackson** [comment]
Hmm, well, maybe this fits with some of your other, deprecated-variable, tickets.

**Comment by haxorof** [comment]
I was a bit funny that you wrote this just a few minutes ago because I just started to look into why the automated tests started to fail now when I ran through everything on Docker CE 19.03. 😄  It seems that the Docker documentation does not really match when they actually removed it. Last time I ran all the tests was on 18.09 and then everything related to `disable-legacy-registry` went fine and did not cause the Docker daemon to fail.

So I can just close this when I have updated my test cases. Will not do anything special here in the role itself.

Many thanks for reporting this!
