### ISSUE TITLE
Centos8: Issues when trying to install plugins

### ISSUE THREAD

**Issue by janorn** [haxorof/ansible-role-docker-ce#131]
### Version Information
Ansible: `2.9.14`
Role: `3.1.1`

### Steps to Reproduce
Install docker with the following variable set.
```
docker_plugins:
  - type: authz
    alias: opa-docker-authz
    name: openpolicyagent/opa-docker-authz-v2:0.4
    args: opa_args="-policy-file /opa/policies/authz.rego"
```

### Expected Behavior
Install complete and docker running.

### Actual Behavior
```
TASK [haxorof.docker_ce : Start Docker daemon] *********************************
task path: /tmp/packer-provisioner-ansible-local/5fa40e28-8833-1f16-ef18-0e1b3a93b684/roles/haxorof.docker_ce/tasks/configure-docker/configure-docker-plugins.yml:4
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [haxorof.docker_ce : Wait for Docker daemon to started] *******************
task path: /tmp/packer-provisioner-ansible-local/5fa40e28-8833-1f16-ef18-0e1b3a93b684/roles/haxorof.docker_ce/tasks/configure-docker/configure-docker-plugins.yml:14
FAILED - RETRYING: Wait for Docker daemon to started (10 retries left).
FAILED - RETRYING: Wait for Docker daemon to started (9 retries left).
FAILED - RETRYING: Wait for Docker daemon to started (8 retries left).
FAILED - RETRYING: Wait for Docker daemon to started (7 retries left).
FAILED - RETRYING: Wait for Docker daemon to started (6 retries left).
FAILED - RETRYING: Wait for Docker daemon to started (5 retries left).
FAILED - RETRYING: Wait for Docker daemon to started (4 retries left).
FAILED - RETRYING: Wait for Docker daemon to started (3 retries left).
FAILED - RETRYING: Wait for Docker daemon to started (2 retries left).
FAILED - RETRYING: Wait for Docker daemon to started (1 retries left).
fatal: [127.0.0.1]: FAILED! => {"attempts": 10, "changed": false, "cmd": "docker info", "delta": "0:00:00.092221", "end": "2020-11-05 14:45:00.318418", "msg": "non-zero return code", "rc": 1, "start": "2020-11-05 14:45:00.226197", "stderr": "errors pretty printing info", "stderr_lines": ["errors pretty printing info"], "stdout": "Client:\n Debug Mode: false\n\nServer:\nERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?", "stdout_lines": ["Client:", " Debug Mode: false", "", "Server:", "ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"]}
```

This seems to be caused by this:
```
TASK [Debug] ***********************************************************************************************************
ok: [127.0.0.1] => {
    "ansible_facts.services['docker.service']": {
        "name": "docker.service",
        "source": "systemd",
        "state": "running",
        "status": "enabled"
    }
}
```

### References
https://github.com/haxorof/ansible-role-docker-ce/blob/9aa3a95c2a498495ae0c0a4de0d962a45adda852/tasks/configure-docker/configure-docker-plugins.yml#L4-L12

**Comment by janorn** [comment]
I can't see any harm in just dropping the when statement. Docker needs to be running to install plugins.
And service is idempotent so if docker is running already nothing will happen.

**Comment by haxorof** [comment]
Did you do similar to what I did here in my test? https://github.com/haxorof/ansible-role-docker-ce/blob/master/tests/experimental/cis/test_cis.yml

It is a bit complicated when installing the authz and have this special logic around it when you for example install it Docker for the first time because then I need to start Docker first without the authz config to be able to download it with the Docker daemon and after that I can configure it and do a restart.

I can try running this test again this weekend and see if that still works.

**Comment by janorn** [comment]
I been running with this plugin all the time. But it seems i haven't stumbled on this in my current systems as they already have a running docker. The new check actually doesn't work properly in systemd environments due to the add suffix ".service" in the ansible_facts.services.

**Comment by haxorof** [comment]
Thanks! I will look into this weekend then.

**Comment by haxorof** [comment]
Just as note to this issue. Changes related to #127 caused this bug.

**Comment by janorn** [comment]
Why do we need this code:

https://github.com/haxorof/ansible-role-docker-ce/blob/dd168c6b4166595fc5a5222d05b014e80219ffee/tasks/configure-docker/configure-docker-plugins.yml#L9-L18

When we need the docker daemon to run to install plugins?

This code is only called if there is plugins to be installed:
https://github.com/haxorof/ansible-role-docker-ce/blob/889da07c63e7aec85440caac93049c26827b4419/tasks/configure-docker.yml#L132-L134

As [ansible service](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/service_module.html) is idempotent. Nothing will happen if the service is already running.

> started/stopped are idempotent actions that will not run commands unless necessary.
restarted will always bounce the service.
reloaded will always reload.

**Comment by haxorof** [comment]
The issue with the plugins is that it needs a Docker daemon to be run with a working configuration for the plugins to be installed. Then different Linux distributions behaves differently (or did in the past) when just enabling the service (not starting it):
https://github.com/haxorof/ansible-role-docker-ce/blob/889da07c63e7aec85440caac93049c26827b4419/tasks/configure-docker.yml#L113-L119

When you the first install the authz plugin then you are not allowed to have that configuration in `/etc/docker/daemon.json` the first time Docker daemon is started because you need to install it before it can be configured. So that is what the extra include related to docker plugin do. 
1. It ensure the daemon is started if not already since some distributions do start it when I actually just telling it to enable it. 
2. Then is starts without the plugin configuration to be able to install the plugins (for example authz)
3. Then reconfigure it with the authz plugin and notify the handler to restart the daemon.

At that time I did that I could not find a better way to do this reconfiguring and restarting all because the Docker daemon itself must be installed to download plugins.

**Comment by janorn** [comment]
I understand but the test is just checking if it's running don't do anything. But the Ansible service module will start it only if it isn't running. And the task after requires the service to be started. So if it isn't running the install will fail. 

Hence we really don't need the when clause. If we came this far we want the daemon to be running to be able to install the plugins in the following tasks. 

Or am I missing something in this particular task file?

**Comment by haxorof** [comment]
Might be that you are not missing something 😄 
I cannot remember exactly why I really did it like that but if was for a reason which seems now to be a bit odd now when you pointing at it. Going to write a ticket where I have to review the logic around plugins and discussion about that can continue there.
