### ISSUE TITLE
Version 3.3.0 forces pip upgrades on RHEL8

### ISSUE THREAD

**Issue by janorn** [haxorof/ansible-role-docker-ce#135]
### Version Information
Ansible: `2.9.0`
Role: `3.3.0`

### Steps to Reproduce
Add following vars: 

```
docker_additional_packages_pip: 
  - "some_pip_pkg"
docker_x_fix_no_zipp_module: false
```` 
To your play.

### Expected Behavior
Install pip packages with current pip.

### Actual Behavior
Forces an upgrade of pip

### References
https://github.com/haxorof/ansible-role-docker-ce/blob/f7f1393336d843e829c053e65c0256cd33d15432/tasks/postinstall.yml#L128-L133

**Comment by haxorof** [comment]
This upgrade of pip was added recently since docker-compose install fails due to new rust dependency added in cryptography library.

What kind of issues does this cause for you?

**Comment by janorn** [comment]
We don't use docker-compose. And really prefer to keep pip managed by the OS supported repository.

**Comment by janorn** [comment]
Which library is required?

**Comment by haxorof** [comment]
docker-compose depends on library cryptography and they added Rust as dependency now which requires upgraded pip version or sometimes cargo library to be installed depending on OS.

Rust dependency is written in the install instructions: https://cryptography.io/en/latest/installation.html

What I can do to introduce one variable for this role to prevent any upgrades of pip if you want? Then you can set that instead of: docker_x_fix_no_zipp_module

**Comment by haxorof** [comment]
I will today add an experimental parameter called `docker_x_skip_pip_auto_upgrade`. This will prevent any PiP upgrade to happen in cases the role it needs it. So you can just use that instead of setting `docker_x_fix_no_zipp_module`.
