### ISSUE TITLE
Running Docker Bench against Role-Provisioned Host

### ISSUE THREAD

**Issue by jamiejackson** [haxorof/ansible-role-docker-ce#14]
I'm new to this role as of today (and just heard of Docker Bench from this project's README). I'm trying this out with the following on a CentOS 7.4 VM:

```yml
  roles:
    - role: haxorof.docker-ce
      docker_enable_audit: true
      docker_daemon_config:
        icc: false
        init: true
        userns-remap: default
        disable-legacy-registry: true
        live-restore: true
        userland-proxy: false
        log-driver: journald
        storage-driver: devicemapper
```

I tried running the [`docker run` from Docker Bench](https://github.com/docker/docker-bench-security/blob/a5a40e80a94bf6fd39c9246e56ff7b3c42436605/README.md#running-docker-bench-for-security), but I hit some hurdles. Here's the first:

```
[root@centos-jenkins-slave vagrant]# docker run -it --net host --pid host --cap-add audit_control \
>     -e DOCKER_CONTENT_TRUST=$DOCKER_CONTENT_TRUST \
>     -v /var/lib:/var/lib \
>     -v /var/run/docker.sock:/var/run/docker.sock \
>     -v /usr/lib/systemd:/usr/lib/systemd \
>     -v /etc:/etc --label docker_bench_security \
>     docker/docker-bench-security
docker: Error response from daemon: cannot share the host's network namespace when user namespaces are enabled.
See 'docker run --help'.
```

How do I run Docker Bench against a host provisioned with this role?

**Comment by haxorof** [comment]
Hi @jamiejackson
First of all I am glad you are trying out my role. The reason why you cannot run Docker Bench in a container like that is because the more secure configuration you now have does now allow you to do that. I have not myself used the container version of Docker bench so I cannot say if it might be possible run. What will work is if you just use git and clone the Docker bench to your machine and just run the bash script. 

Hope that will work for you! 

Cheers
@haxorof

**Comment by jamiejackson** [comment]
Got it, thanks. This works:

```
git clone https://github.com/docker/docker-bench-security.git
cd docker-bench-security
sudo sh docker-bench-security.sh
```

Now to pore over the items in the report.
