### ISSUE TITLE
Commit comment format

### ISSUE THREAD

**Issue by jamiejackson** [haxorof/ansible-role-docker-ce#23]
The format of `Fixes #N`, (e.g., "Fixes #20") makes the changelog difficult to use. What do you think about commenting in a format along the lines of "Support for Ubuntu and Debian #20"?

**Comment by haxorof** [comment]
Hi @jamiejackson 
I have not thought so much about the commit log more than make it easy to handle issues. Reason I commits using "Fixes #N" is because there is a hook in github which then also closes the issue automatically. 😄 However, sure I can add some more text to the commit message just to make it more clear when you only look at the commit log.

However I have created a changelog which I keep up-to-date.
https://github.com/haxorof/ansible-role-docker-ce/blob/master/CHANGELOG.md

Have you seen the changelog I have? or do you just look at the commit log usually?

Cheers!

**Comment by jamiejackson** [comment]
Ah, thanks. The CHANGELOG.md is good. I think I'd noticed it at one point, but forgot about it. Since lots of projects don't have one, I'm used to looking at the comments.
