### ISSUE TITLE
starting setns process caused \"fork/exec /proc/self/exe: no such file or directory\""

### ISSUE THREAD

**Issue by jamiejackson** [haxorof/ansible-role-docker-ce#33]
https://access.redhat.com/solutions/2991041

`Red Hat Enterprise Linux Server release 7.4 (Maipo)` (but I assume it would happen on CentOS 7.4, too).

We into this today after an app server became inaccessible. We got the aforementioned error when `docker exec`ing into the container (then afterward, we got `driver failed programming external connectivity on endpoint` when trying to restart the container--not sure if this bit is related or not).

I performed a shotgun fix by removing all containers, restarting the docker service, and re-running the docker-compose up on the stack.

From the KB article:

> Root Cause
> * docker on RHEL does not support daemon restart and live-restore.
> * docker systemd unit file has 'MountFlag=true enabled. This is not compatible with live-restore.

I know we're [setting `MountFlags=slave`](https://github.com/haxorof/ansible-role-docker-ce/blob/5128382e4281611ba7c64428c02a2b304f1a8b9d/tasks/kernel-3-mount-fixes.yml#L6), but I'm not sure if that's associated with this root cause. 

I wonder if the role should prevent `live-restore` with certain OS versions or configurations.

**Comment by haxorof** [comment]
Hmm.. the slave mount flag was added because in CentOS if was very easy to end up with problems when you used volume mapping. So based on what you reference here it might be good to have a variable to not always apply the slave mount flag as it is done today.

Then about having an logic for `live-restore` I do not know. If too much logic is introduced looking at variable `docker_daemon_config` then when variable `docker_daemon_config_file` is used then the role will behave too different if to much logic relies on `docker_daemon_config`. One best effort thing that this could do is to fail before execution if it detects some configuration which will cause problems on certain distributions but do not really know what is best to do.

**Comment by jamiejackson** [comment]
> Hmm.. the slave mount flag was added because in CentOS if was very easy to end up with problems when you used volume mapping. So based on what you reference here it might be good to have a variable to not always apply the slave mount flag as it is done today.

Please see #34 for a question about the slave mount flag (I wasn't sure I'd be muddying the water in this ticket).

I'm still thinking about live-restore issue & the rest of your response...

**Comment by haxorof** [comment]
https://github.com/moby/moby/issues/35873

**Comment by jamiejackson** [comment]
Let me take a step back:

Given the state of the current, stable Docker and OS (I'm getting 18.03.0-ce on RHEL 7.4), do you interpret (from the of the various OS/docker bugs/workarounds/fixes) that I can have both:
* Containers stay up during daemon restart (which I _think_ I want, but I don't know enough about the feature to know whether/why I might not want it).
* Volume mounts work as expected

...if I don't have `MountFlags` explicitly set and I have `live-restore: yes`? If so, that's the combo I'm going to try out for a while. (Although the role will need the `MountFlags` fix to be toggleable as described in #34.)

**Comment by haxorof** [comment]
Closing this issue because now it seems MountFlags cause problems in CentOS when running Docker 18.09 (#76). Going to set this role NOT to apply the MountFlags option by default.
